<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <Version>1.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
    <Reference Include="vJoyInterfaceWrap">
      <HintPath>..\..\libs\x64\vJoyInterfaceWrap.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyVJoyNative" AfterTargets="Build">
    <Copy SourceFiles="..\..\libs\x64\vJoyInterfaceWrap.dll;..\..\libs\x64\vJoyInterface.dll" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
